processors:
  - '@mapbox/stylelint-processor-arbitrary-tags'
plugins:
  - stylelint-prettier
extends:
  - stylelint-prettier/recommended
ignoreFiles:
  - '**/*.js'
  - '*.js'
  - '**/*.ts'
  - '*.ts'
rules:
  prettier/prettier: true

  # To solve confliction with Prettier
  number-leading-zero: null

  at-rule-empty-line-before: null
  max-nesting-depth: [2, {
    'ignoreAtRules': [
      'function',
      'if',
      'else',
      'return',
      'each',
      'mixin',
      'media',
      'include'
    ],
  }]
  no-empty-source: null
